import { optimizedFonts } from "@/utilities/fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${optimizedFonts.variable} w-full h-full`}>
      <body className="font-estedad font-body-xl w-full h-full">
        {children}
      </body>
    </html>
  );
}
